name:
  CI/CD pipe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up go
      uses: actions/setup-go@v3
      with: 
        go-version: '1.22'

    - name: Cache go modules
      uses: actions/cache@v2
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
        restore_keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./internal/handler -v

    - name: Build the go app
      run: go build -o app /cmd/server

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Render
      run: |
        curl -fsSL https://render.com/deploy/SOME_DEPLOY_KEY | bash
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
